freelancer/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('profile/', include('freelancer_app.urls'))
]

freelancer_app/urls.py
from django.urls import path
from .views import *

app_name = 'freelancer_app'

urlpatterns = [
    
    path('', ProfileView.as_view(), name = 'profile'),
    path('create/', ProfileCreateView.as_view(),name = 'create_profile'),
    path('view/<int:pk>/', ProfileDetailView.as_view(), name = 'profile_view'),
    path('update/<int:pk>/', ProfileUpdateView.as_view(), name = 'edit_profile'),
    path('delete/<int:pk>/', ProfileDeleteView.as_view(), name = 'delete_profile'),



]

freelancer_app/models.py
from django.db import models

# Create your models here.

class Profile(models.Model):
    name = models.CharField(max_length = 255)
    email = models.EmailField(unique=True)
    phone_no = models.CharField(max_length=10)
    
    def __str__(self):
        return self.name

class Skill(models.Model):
    user = models.ForeignKey(Profile, on_delete = models.CASCADE)
    name = models.CharField(max_length = 255)
    proficiency = models.CharField(max_length = 20)

    def __str__(self):
        return self.name

class Language(models.Model):
    user = models.ForeignKey(Profile, on_delete = models.CASCADE)
    language = models.CharField(max_length=255)
    proficiency = models.CharField(max_length=32)

    def __str__(self):
        return self.language

freelancer_app/forms.py
from django import forms
from .models import *


class ProfileCreateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['name', 'email', 'phone_no']

freelancer_app/views.py
import random

from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views.generic import (CreateView, DeleteView, DetailView, FormView,
                                  ListView, TemplateView, UpdateView, View)

from django_seed import Seed

from .forms import *
from .models import *

seeder = Seed.seeder()

# Create your views here.

class ProfileView(ListView):
    model = Profile
    # queryset = Profile.objects.all()
    template_name = 'freelancer_app/profile_list.html'    
    
    def get_queryset(self):
        data = Profile.objects.all()
        return data 

class ProfileCreateView(CreateView):
    template_name = 'freelancer_app/create_profile.html'
    model = Profile
    form_class = ProfileCreateForm

    def post(self, request):
        if request.method == 'POST':
            form = ProfileCreateForm(request.POST)
            if form.is_valid():
                name = request.POST.get('name')
                email = request.POST.get('email')
                phone_no = request.POST.get('phone_no')
                profile = Profile(name = name, email=email, phone_no=phone_no)
                profile.save()
                # select_data = 
                profile_new = Profile.objects.get(email = email)
                seeder.add_entity(Language, 5, {
                    'user':profile_new,
                    'language':seeder.faker.name(),                    
                    'proficiency':random.choice(('Good','Bad', 'Very Good'))
                })
                seeder.add_entity(Skill, 5, {
                    'user':profile_new,
                    'name':seeder.faker.name(),                    
                    'proficiency':random.choice(('Good','Bad', 'Very Good'))
                })
                seeder.execute()
                return HttpResponseRedirect(reverse("freelancer_app:profile"))
            else:
                return HttpResponseRedirect(reverse("freelancer_app:profile"))

class ProfileDetailView(DetailView):
    template_name = 'freelancer_app/profile_detail.html'
    model = Profile

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        profile_id = self.kwargs.get('pk')
        profile = Profile.objects.get(id = profile_id)
        context['profile'] = profile
        skill = Skill.objects.filter(user__id = profile_id)
        context['skill'] = skill
        context['lan'] = Language.objects.filter(user__id = profile_id)
        return context

class ProfileUpdateView(UpdateView):
    template_name = 'freelancer_app/edit_profile.html'
    model = Profile
    form_class = ProfileCreateForm
    success_url = reverse_lazy('freelancer_app:profile')

class ProfileDeleteView(DeleteView):
    model = Profile
    success_url = reverse_lazy('freelancer_app:profile')

freelancer_app/templates/freelancer_app/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Frreelancer Profile &nbsp; {% block title  %}   {% endblock title %} </title>

        <!-- BEGIN META -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="keywords" content="your,keywords">
        <meta name="description" content="Short explanation about this website">
        <!-- END META -->

        <!-- BEGIN STYLESHEETS -->
        <link href='http://fonts.googleapis.com/css?family=Roboto:300italic,400italic,300,400,500,700,900' rel='stylesheet' type='text/css'/>
        <link type="text/css" rel="stylesheet" href="{% static 'administration/css/theme-default/bootstrap.css' %}" />
        <link type="text/css" rel="stylesheet" href="{% static 'administration/css/theme-default/materialadmin.css' %}" />
        <link type="text/css" rel="stylesheet" href="{% static 'administration/css/theme-default/font-awesome.min.css' %}" />
        <link type="text/css" rel="stylesheet" href="{% static 'administration/css/theme-default/material-design-iconic-font.min.css' %}" />
        <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/jplayer/2.9.2/skin/blue.monday/css/jplayer.blue.monday.min.css"/>
        <link href="//cdn.bootcss.com/bootstrap-datetimepicker/4.17.44/css/bootstrap-datetimepicker.min.css" rel="stylesheet">


        <link href="//cdn.datatables.net/1.10.11/css/jquery.dataTables.min.css" rel="stylesheet" media="screen">
        <script src="{% static 'administration/js/libs/jquery/jquery-1.11.2.min.js' %}">
        </script>
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jplayer/2.9.2/jplayer/jquery.jplayer.min.js"></script>
        {% block head %}{% endblock %}
    </head>
    <body class="menubar-hoverable header-fixed menubar-pin ">
        <header id="header" >
            <div class="headerbar">
                <div class="headerbar-left">
                    <ul class="header-nav header-nav-options">
                        <li class="header-nav-brand" >
                            <div class="brand-holder">
                                <a href="{% url 'freelancer_app:profile' %}">
                                    <span class="text-lg text-bold text-primary">Freelancer Profile</span>
                                </a>
                            </div>
                        </li>
                    </ul>
                </div>
                <div class="headerbar-right">
                    <ul class="header-nav header-nav-options">
                        <li>
                            <form class="navbar-search" role="search">
                                <div class="form-group">
                                    <input type="text" class="form-control" name="headerSearch" placeholder="Enter your keyword">
                                </div>
                                <button type="submit" class="btn btn-icon-toggle ink-reaction"><i class="fa fa-search"></i></button>
                            </form>
                        </li>
                    </ul><!--end .header-nav-options -->
                    <!--end .header-nav-profile -->
                </div><!--end #header-navbar-collapse -->
            </div>
        </header>
        <!-- END HEADER-->
        
        <!-- BEGIN BASE-->
        <div id="">
            <div class="offcanvas">
            </div>
            {% block maincontent %}                
        
            {% endblock maincontent %}
         
        </div>

        <!-- BEGIN JAVASCRIPT -->
        
        <script src="{% static 'administration/js/libs/jquery/jquery-migrate-1.2.1.min.js' %}"></script>
        <script src="{% static 'administration/js/libs/bootstrap/bootstrap.min.js' %}"></script>
        <script src="{% static 'administration/js/libs/spin.js/spin.min.js' %}"></script>
        <script src="{% static 'administration/libs/autosize/jquery.autosize.min.js' %}"></script>
        <script src="{% static 'administration/libs/nanoscroller/jquery.nanoscroller.min.js' %}"></script>
        <script src="{% static 'administration/core/source/App.js' %}"></script>
        <script src="{% static 'administration/core/source/AppNavigation.js' %}"></script>
        <script src="{% static 'administration/core/source/AppOffcanvas.js' %}"></script>
        <script src="{% static 'administration/core/source/AppCard.js' %}"></script>
        <script src="{% static 'administration/core/source/AppForm.js' %}"></script>
        <script src="{% static 'administration/core/source/AppNavSearch.js' %}"></script>
        <!-- <script src="{% static 'administration/core/source/AppVendor.js' %}"></script> -->
        <script src="{% static 'administration/core/demo/Demo.js' %}"></script>
        
        <!-- END JAVASCRIPT -->
        <script src="//cdn.bootcss.com/jquery/3.0.0/jquery.min.js"></script>
        <script src="//cdn.bootcss.com/moment.js/2.17.1/moment.min.js"></script>
        <script src="//cdn.bootcss.com/bootstrap-datetimepicker/4.17.44/js/bootstrap-datetimepicker.min.js"></script>


        <script type="text/javascript">
            $('body').on('hidden.bs.modal', '.modal', function () {
                $(this).removeData('bs.modal');
            });
        </script>
        <script>
            $(function () {
                $('.datetime-input').datetimepicker({
                    format:'YYYY-MM-DD HH:mm:ss'
                });
            });
        </script>

    </body>
    {% block script %}
        <script src="//cdn.datatables.net/1.10.11/js/jquery.dataTables.min.js"></script>
    {% endblock %}
</html>

freelancer_app/templates/freelancer_app/create_profile.html
{% extends "freelancer_app/base.html" %}
{% block title%} Create Profile {% endblock title %}
{% block maincontent %}
    <div id="content">
        <section>
            <div class="section-header">
                <ol class="breadcrumb">
                    <li><a href="">Profile</a></li>
                    <li class="active">Form</li>
                </ol>
            </div>
            <div class="section-body">
                <div class="card">
                    <div class="card-body">
                        <form class="form" action="{% url 'freelancer_app:create_profile' %} " method="POST" enctype="multipart/form-data">{% csrf_token %}
                            {{ form.as_p }}
                            {{ form.media }}
                            <div class="form-group">
                                <input type="submit" id="submit" class="btn btn-success" value="Save">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </section>
    </div>
{% endblock maincontent %}

freelancer_app/templates/freelancer_app/edit_profile.html
{% extends "freelancer_app/base.html" %}
{% block title%} Create Profile {% endblock title %}
{% block maincontent %}
    <div id="content">
        <section>
            <div class="section-header">
                <ol class="breadcrumb">
                    <li><a href="">Profile</a></li>
                    <li class="active">Form</li>
                </ol>
            </div>
            <div class="section-body">
                <div class="card">
                    <div class="card-body">
                        <form class="form" action="#" method="POST" enctype="multipart/form-data">{% csrf_token %}
                            {{ form.as_p }}
                            <div class="form-group">
                                <input type="submit" id="submit" class="btn btn-success" value="Save">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </section>
    </div>
{% endblock maincontent %}

freelancer_app/templates/freelancer_app/profile_confirm_delete.html
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">&times;</button>
    <h4 class="modal-title">Modal Header</h4>
</div>
<div class="modal-body">
    <div class="modal-body">
        <p><strong>Are you sure to delete this profile ?</strong></p>
    </div>
    <div class="modal-footer">
        <form action="{% url 'freelancer_app:delete_profile' object.id %}" method="POST">
            {% csrf_token %}
            <button class='btn btn-danger' type="submit">Yes, Delete</button>
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </form>
    </div>
</div>

freelancer_app/templates/freelancer_app/profile_detail.html
{% extends "freelancer_app/base.html" %}
{% block title%} Profile List{% endblock title %}
{% block maincontent %}
<div id="content">
    <section>
        <div class="section-body">
            <div class="card">
                <div class="card-body">
                    <div class="row">

                        <div class="">
                            <u>
                                <h3 class="">{{object.name}} Profile</h3>
                            </u>
                        </div>

                    </div>
                    <div>
                        <table class="table">

                            <tbody>
                                <tr>
                                    <th>ID</th>
                                    <td>{{profile.id}}</td>
                                </tr>
                                <tr>
                                    <th>Name</th>
                                    <td>{{profile.name}}</td>
                                </tr>
                                <tr>
                                    <th>Email</th>
                                    <td>{{profile.email}}</td>
                                </tr>
                                <tr>
                                    <th>Phone no</th>
                                    <td>{{profile.phone_no}}</td>
                                </tr>
                            </tbody>

                        </table>
                        <div class="row">
                            <div class="col-md-6">
                                <u>
                                    <h3 class="">Skill</h3>
                                </u>
                                <table class="table">
                                    <thead>

                                        <tr>
                                            <th>Skill</th>
                                            <th>Proficiency</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for i in skill%}
                                        <tr>
                                            <th>{{i.name}}</th>
                                            <td>{{i.proficiency}}</td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>

                            <div class="col-md-6">
                                <u>
                                    <h3 class="">Languages</h3>
                                </u>
                                <table class="table">
                                    <thead>

                                        <tr>
                                            <th>Language</th>
                                            <th>Proficiency</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for i in lan %}
                                        <tr>
                                            <th>{{i.language}}</th>
                                            <td>{{i.proficiency}}</td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
{% endblock maincontent %}

freelancer_app/templates/freelancer_app/profile_list.html
{% extends "freelancer_app/base.html" %}
{% block title%} Profile List{% endblock title %}
{% block maincontent %}
<div id="content">
    <section>
        <div class="section-body">
            <div class="card">
                <div class="card-body">
                    <div class="row">

                        <div class="col-md-10">
                            <h3 class="text-center">Freelancer Profile</h3>
                        </div>
                        <div class="col-md-2">
                            <a href="{% url 'freelancer_app:create_profile' %}"><button class="align-right">Add New <i class="fa fa-plus"></i></button></a>
                        </div>
                    </div>
                    <div>
                        <table class="table">
                            <thead>
                                <tr>
                                    <th scope="col">Id</th>
                                    <th scope="col">Name</th>
                                    <th scope="col">Email</th>
                                    <th scope="col">Phone</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for i in object_list %}
                                <tr>
                                    <th>{{i.id}}</th>
                                    <td>{{i.name|truncatechars:30}}</td>
                                    <td>{{i.email}}</td>
                                    <td>{{i.phone_no}}</td>
                                    <td>
                                        <a class="create-btn btn" data-toggle="modal" data-target="#myModal" data-url="{% url 'freelancer_app:delete_profile' i.id %}"><button>Delete</button></a>
                                        <a href="{% url 'freelancer_app:edit_profile' i.id %}"><button>Edit</button></a>
                                        <a href="{% url 'freelancer_app:profile_view' i.id %}"><button>View</button></a>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

    <!-- Modal Start -->
    <div id="myModal" class="modal fade" role="dialog">
        <div class="modal-dialog">          
          <!-- Modal content-->
          <div class="modal-content">
            
          </div>          
        </div>
      </div>
<!-- End Modal -->

{% endblock maincontent %}

{% block script %}

<script>
    $('.create-btn').click(function(){
        /* 
            AJAX Request
            URL, METHOD defualt = GET, DATA, SUCCESS, ERROR
        */
        var url = $(this).data('url');
        $.ajax({
            url:url,
            method:'GET',
            success:function(data){
                $('.modal-content').empty();
                $('.modal-content').append(data);
            },
            error:function(data){
                console.log(data);
            },
        });
    });
</script>
{% endblock %}